[build]
  # Comando para construir el sitio
  command = "npm run build"
  
  # Directorio de publicación, en este caso, la raíz del proyecto
  publish = "."

[redirects]
  # Redirige todas las solicitudes que no coinciden con archivos existentes a index.html
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200